[package]
name = "cargopool"
version = "0.1.0"
edition = "2023_10"

[dependencies]
starknet = ">=2.4.1"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.13.1" }
alexandria_storage = { git = "https://github.com/keep-starknet-strange/alexandria.git" }

[[target.starknet-contract]]
sierra = true
casm = true